import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-managed-print-copier-lease-audit",
  "engine": "recovery",
  "title": "Managed Print & Copier Lease Audit",
  "shortTitle": "Managed Print and Copier Lease Audit",
  "tagline": "Audit device leases, meter usage, included allowances, supplies, service credits, and end-of-term charges.",
  "industry": "Office Technology Cost Recovery",
  "buyer": "Enterprises, schools, and healthcare systems",
  "uiPort": 4724,
  "apiPort": 5724,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Managed Print & Copier Lease Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits in one accountable workflow. Audit device leases, meter usage, included allowances, supplies, service credits, and end-of-term charges.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Managed Print & Copier Lease Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("lease-agreement-library","MPC01","Lease agreement library","Execute lease agreement library using lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits.","Produce a governed lease agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Device Fleet","text","Vendor / Device Fleet · Standard Case"],["caseReference","Lease agreement library Reference","text","MPC01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1621250],["supportedAmount","Evidence-Supported Amount","currency",1361850],["domainDriver","Charge Type","select","Lease rent",["Lease rent","Usage click","Service supply"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Lease agreement library case","Device serial registry case","Meter read ingestion case","Included volume calculation case","Mono color click rate case"]}),
feature("device-serial-registry","MPC02","Device serial registry","Execute device serial registry using lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits.","Produce a governed device serial registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Device Fleet","text","Vendor / Device Fleet · Standard Case"],["caseReference","Device serial registry Reference","text","MPC02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1621250],["supportedAmount","Evidence-Supported Amount","currency",1361850],["domainDriver","Charge Type","select","Lease rent",["Lease rent","Usage click","Service supply"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Lease agreement library case","Device serial registry case","Meter read ingestion case","Included volume calculation case","Mono color click rate case"]}),
feature("meter-read-ingestion","MPC03","Meter read ingestion","Execute meter read ingestion using lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits.","Produce a governed meter read ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Device Fleet","text","Vendor / Device Fleet · Standard Case"],["caseReference","Meter read ingestion Reference","text","MPC03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1621250],["supportedAmount","Evidence-Supported Amount","currency",1361850],["domainDriver","Charge Type","select","Lease rent",["Lease rent","Usage click","Service supply"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Lease agreement library case","Device serial registry case","Meter read ingestion case","Included volume calculation case","Mono color click rate case"]}),
feature("included-volume-calculation","MPC04","Included volume calculation","Execute included volume calculation using lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits.","Produce a governed included volume calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Device Fleet","text","Vendor / Device Fleet · Standard Case"],["caseReference","Included volume calculation Reference","text","MPC04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1621250],["supportedAmount","Evidence-Supported Amount","currency",1361850],["domainDriver","Charge Type","select","Lease rent",["Lease rent","Usage click","Service supply"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Lease agreement library case","Device serial registry case","Meter read ingestion case","Included volume calculation case","Mono color click rate case"]}),
feature("mono-color-click-rate","MPC05","Mono color click rate","Execute mono color click rate using lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits.","Produce a governed mono color click rate decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Device Fleet","text","Vendor / Device Fleet · Standard Case"],["caseReference","Mono color click rate Reference","text","MPC05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1621250],["supportedAmount","Evidence-Supported Amount","currency",1361850],["domainDriver","Charge Type","select","Lease rent",["Lease rent","Usage click","Service supply"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Lease agreement library case","Device serial registry case","Meter read ingestion case","Included volume calculation case","Mono color click rate case"]}),
feature("supply-inclusion-control","MPC06","Supply inclusion control","Execute supply inclusion control using lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits.","Produce a governed supply inclusion control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Device Fleet","text","Vendor / Device Fleet · Standard Case"],["caseReference","Supply inclusion control Reference","text","MPC06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1621250],["supportedAmount","Evidence-Supported Amount","currency",1361850],["domainDriver","Charge Type","select","Lease rent",["Lease rent","Usage click","Service supply"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Lease agreement library case","Device serial registry case","Meter read ingestion case","Included volume calculation case","Mono color click rate case"]}),
feature("service-downtime-credit","MPC07","Service downtime credit","Execute service downtime credit using lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits.","Produce a governed service downtime credit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Device Fleet","text","Vendor / Device Fleet · Standard Case"],["caseReference","Service downtime credit Reference","text","MPC07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1621250],["supportedAmount","Evidence-Supported Amount","currency",1361850],["domainDriver","Charge Type","select","Lease rent",["Lease rent","Usage click","Service supply"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Lease agreement library case","Device serial registry case","Meter read ingestion case","Included volume calculation case","Mono color click rate case"]}),
feature("device-relocation-tracking","MPC08","Device relocation tracking","Execute device relocation tracking using lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits.","Produce a governed device relocation tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Device Fleet","text","Vendor / Device Fleet · Standard Case"],["caseReference","Device relocation tracking Reference","text","MPC08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1621250],["supportedAmount","Evidence-Supported Amount","currency",1361850],["domainDriver","Charge Type","select","Lease rent",["Lease rent","Usage click","Service supply"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Lease agreement library case","Device serial registry case","Meter read ingestion case","Included volume calculation case","Mono color click rate case"]}),
feature("duplicate-device-billing","MPC09","Duplicate device billing","Execute duplicate device billing using lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits.","Produce a governed duplicate device billing decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Device Fleet","text","Vendor / Device Fleet · Standard Case"],["caseReference","Duplicate device billing Reference","text","MPC09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1621250],["supportedAmount","Evidence-Supported Amount","currency",1361850],["domainDriver","Charge Type","select","Lease rent",["Lease rent","Usage click","Service supply"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Lease agreement library case","Device serial registry case","Meter read ingestion case","Included volume calculation case","Mono color click rate case"]}),
feature("property-tax-fee-review","MPC10","Property tax fee review","Execute property tax fee review using lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits.","Produce a governed property tax fee review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Device Fleet","text","Vendor / Device Fleet · Standard Case"],["caseReference","Property tax fee review Reference","text","MPC10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1621250],["supportedAmount","Evidence-Supported Amount","currency",1361850],["domainDriver","Charge Type","select","Lease rent",["Lease rent","Usage click","Service supply"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Lease agreement library case","Device serial registry case","Meter read ingestion case","Included volume calculation case","Mono color click rate case"]}),
feature("early-termination-audit","MPC11","Early termination audit","Execute early termination audit using lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits.","Produce a governed early termination audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Device Fleet","text","Vendor / Device Fleet · Standard Case"],["caseReference","Early termination audit Reference","text","MPC11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1621250],["supportedAmount","Evidence-Supported Amount","currency",1361850],["domainDriver","Charge Type","select","Lease rent",["Lease rent","Usage click","Service supply"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Lease agreement library case","Device serial registry case","Meter read ingestion case","Included volume calculation case","Mono color click rate case"]}),
feature("invoice-recalculation","MPC12","Invoice recalculation","Execute invoice recalculation using lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits.","Produce a governed invoice recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Device Fleet","text","Vendor / Device Fleet · Standard Case"],["caseReference","Invoice recalculation Reference","text","MPC12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1621250],["supportedAmount","Evidence-Supported Amount","currency",1361850],["domainDriver","Charge Type","select","Lease rent",["Lease rent","Usage click","Service supply"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Lease agreement library case","Device serial registry case","Meter read ingestion case","Included volume calculation case","Mono color click rate case"]}),
feature("vendor-dispute-workflow","MPC13","Vendor dispute workflow","Execute vendor dispute workflow using lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits.","Produce a governed vendor dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Device Fleet","text","Vendor / Device Fleet · Standard Case"],["caseReference","Vendor dispute workflow Reference","text","MPC13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1621250],["supportedAmount","Evidence-Supported Amount","currency",1361850],["domainDriver","Charge Type","select","Lease rent",["Lease rent","Usage click","Service supply"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Lease agreement library case","Device serial registry case","Meter read ingestion case","Included volume calculation case","Mono color click rate case"]}),
feature("credit-reconciliation","MPC14","Credit reconciliation","Execute credit reconciliation using lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Device Fleet","text","Vendor / Device Fleet · Standard Case"],["caseReference","Credit reconciliation Reference","text","MPC14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1621250],["supportedAmount","Evidence-Supported Amount","currency",1361850],["domainDriver","Charge Type","select","Lease rent",["Lease rent","Usage click","Service supply"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Lease agreement library case","Device serial registry case","Meter read ingestion case","Included volume calculation case","Mono color click rate case"]}),
feature("fleet-device-analytics","MPC15","Fleet device analytics","Execute fleet device analytics using lease agreements, devices, meter reads, included volumes, click rates, supplies, service events, relocations, terminations, invoices, and credits.","Produce a governed fleet device analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Device Fleet","text","Vendor / Device Fleet · Standard Case"],["caseReference","Fleet device analytics Reference","text","MPC15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1621250],["supportedAmount","Evidence-Supported Amount","currency",1361850],["domainDriver","Charge Type","select","Lease rent",["Lease rent","Usage click","Service supply"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Lease agreement library case","Device serial registry case","Meter read ingestion case","Included volume calculation case","Mono color click rate case"]})
]);
